# Generated by Django 5.1.7 on 2025-08-09 11:57

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Аватарка')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('first_name', models.CharField(default='Имя', max_length=120, verbose_name='Имя')),
                ('last_name', models.CharField(default='Фамилия', max_length=120, verbose_name='Фамилия')),
                ('surname', models.CharField(blank=True, max_length=120, null=True, verbose_name='Отчество')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True, verbose_name='Пол')),
                ('about', models.CharField(blank=True, max_length=300, null=True)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram chat ID')),
                ('citizenship', models.CharField(blank=True, max_length=100, null=True, verbose_name='Гражданство')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('worker', 'Worker'), ('director', 'Director')], default='worker', max_length=8, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_fired', models.BooleanField(default=False, verbose_name='Уволен')),
                ('termination_reason', models.TextField(blank=True, null=True, verbose_name='Основание увольнения')),
                ('termination_order_date', models.DateField(blank=True, null=True, verbose_name='Дата приказа увольнения')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('is_employee', models.BooleanField(default=False, verbose_name='Является мастером')),
                ('schedule_start', models.TimeField(default=datetime.time(9, 0))),
                ('schedule_end', models.TimeField(default=datetime.time(18, 0))),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('services', models.ManyToManyField(blank=True, related_name='masters', to='leads.service', verbose_name='Предоставляемые услуги')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.SmallIntegerField(choices=[(1, 'monday'), (2, 'tuesday'), (3, 'wednesday'), (4, 'thursday'), (5, 'friday'), (6, 'saturday'), (7, 'sunday')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало рабочего дня')),
                ('end_time', models.TimeField(verbose_name='Конец рабочего дня')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Рабочий день',
                'verbose_name_plural': 'Расписания сотрудников',
                'ordering': ['weekday'],
            },
        ),
    ]
