# Generated by Django 5.1.7 on 2025-04-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_employee_user_schedule_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
