# Generated by Django 5.1.7 on 2025-04-17 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employeeschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeschedule',
            options={'ordering': ['weekday'], 'verbose_name': 'Рабочий день', 'verbose_name_plural': 'Расписания сотрудников'},
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='weekday',
            field=models.SmallIntegerField(choices=[(1, 'monday'), (2, 'tuesday'), (3, 'wednesday'), (4, 'thursday'), (5, 'friday'), (6, 'saturday'), (7, 'sunday')], verbose_name='День недели'),
        ),
    ]
