# Generated by Django 5.1.7 on 2025-08-09 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название услуги')),
                ('duration', models.IntegerField(default=30, verbose_name='Длительность (мин)')),
                ('price', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_long', models.BooleanField(default=False)),
                ('is_additional', models.BooleanField(default=False, verbose_name='Дополнительная услуга')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('prepayment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на оплату')),
                ('is_confirmed', models.BooleanField(blank=True, default=None, null=True)),
                ('prepayment_paid', models.BooleanField(default=False, verbose_name='Предоплата получена')),
                ('date', models.DateField(blank=True, null=True)),
                ('reminder_minutes', models.IntegerField(choices=[(30, 'За 30 минут'), (60, 'За 1 час'), (120, 'За 2 часа'), (180, 'За 3 часа'), (1440, 'За 1 день')], default=60, verbose_name='Время напоминания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ['-created_at'],
            },
        ),
    ]
