# Generated by Django 5.1.7 on 2025-08-09 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='parent_services',
            field=models.ManyToManyField(blank=True, related_name='additional_services', to='leads.service'),
        ),
        migrations.AddField(
            model_name='lead',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='leads', to='leads.service'),
        ),
    ]
