# Generated by Django 5.1.7 on 2025-04-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_service_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лид', 'verbose_name_plural': 'Лиды'},
        ),
    ]
