# Generated by Django 5.1.7 on 2025-04-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='service',
        ),
        migrations.AddField(
            model_name='lead',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='leads.service'),
        ),
    ]
