# Generated by Django 5.1.7 on 2025-04-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_client_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='service',
            field=models.ManyToManyField(blank=True, to='leads.service'),
        ),
    ]
