# Generated by Django 5.1.7 on 2025-04-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_lead_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='is_confirmed',
            field=models.BooleanField(default=None),
        ),
    ]
