# Generated by Django 5.1.7 on 2025-04-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_lead_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='is_confirmed',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
