# Generated by Django 5.1.7 on 2025-04-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_remove_lead_service_lead_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_long',
            field=models.BooleanField(default=False),
        ),
    ]
