# Generated by Django 5.1.7 on 2025-04-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_service_is_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
