# Generated by Django 5.1.7 on 2025-05-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_lead_date_alter_lead_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='reminder_minutes',
            field=models.IntegerField(choices=[(30, 'За 30 минут'), (60, 'За 1 час'), (120, 'За 2 часа'), (180, 'За 3 часа'), (1440, 'За 1 день')], default=60, verbose_name='Время напоминания'),
        ),
    ]
