# Generated by Django 5.1.7 on 2025-06-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_services_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_additional',
            field=models.BooleanField(default=False, verbose_name='Дополнительная услуга'),
        ),
    ]
