# Generated by Django 5.1 on 2025-07-01
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_alter_service_is_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='payment_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на оплату'),
        ),
    ]
