# Generated by Django 5.1.7 on 2025-06-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_lead_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='prepayment_paid',
            field=models.BooleanField(default=False, verbose_name='Предоплата получена'),
        ),
    ]
