# Generated by Django 5.1.7 on 2025-07-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_alter_service_options_service_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='parent_service',
        ),
        migrations.AddField(
            model_name='service',
            name='parent_service',
            field=models.ManyToManyField(blank=True, related_name='additional_services', to='leads.service'),
        ),
    ]
