# Generated by Django 5.1.7 on 2025-07-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_remove_service_parent_service_service_parent_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='parent_service',
            new_name='parent_services',
        ),
    ]
